name: Deploy Node Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t abhinavdogra003768/backend  .
      - name: Publish Image to docker hub
        run: docker push abhinavdogra003768/backend:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull abhinavdogra003768/backend:latest 
      - name: Delete old container
        run: docker rm -f backend-container  
      - name: Run Docker Container
        run: docker run -d -p 8000:8000 --name backend-container \ -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' \ -e ALLOWED_ORIGINS='${{ secrets.ALLOWED_ORIGINS }}' \ abhinavdogra003768/backend
