name: deploy backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Free up disk space
        run: docker system prune -a -f

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin     

      - name: Build Docker Image
        run: docker build -t abhinavdogra003768/backend .

      - name: Publish Image to Docker Hub
        run: docker push abhinavdogra003768/backend:latest 

  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Check Docker Installation
        run: docker --version

      - name: Pull latest image from Docker Hub
        run: docker pull abhinavdogra003768/backend:latest 

      - name: Remove old container (if exists)
        run: docker rm -f backend-container || true

      - name: Remove old image (if exists)
        run: docker rmi -f abhinavdogra003768/backend:latest || true

      - name: Run Docker Container
        run: docker run -d -p 8000:8000 --name backend-container --restart unless-stopped -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' abhinavdogra003768/backend
